version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5433:5432"  # Thay đổi cổng này nếu cần
  redis:
    image: redis:latest
    ports:
      - "6380:6379"  # Thay đổi cổng này nếu cần
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_MASTER_KEY: "09a419d8ab3b52e4ca7c6c330986e348"

volumes:
  redis:
  postgres:
